on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed
jobs:
  msgram_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Action MeasureSoftGram
        uses: fga-eps-mds/2024.1-MeasureSoftGram-Action@christian/feat/US-006
        id: msgram
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }} # Token do GitHub
          sonarProjectKey: "" # (opcional) Chave do projeto no SonarQube
          msgramServiceToken: "Token 260780eadb7126db154e2669ad59117237293d05" # Token para acessar o serviço MeasureSoftGram
          productName: "GolangApp" # Nome do produto
          workflowName: 'build'